import { uniqueId } from 'lodash';

import {
  IconAddressBook,
  IconPackage,
  IconBriefcase,
  IconFileText,
  IconReceipt,
  IconShoppingCart,
  IconShield,
  IconUsers,
  IconClipboardCheck,
  IconSettings,
  IconPoint,
  IconLayoutDashboard,
  IconHammer,
  IconFileInvoice,
  IconWallet,
  IconCoin,
  IconTruckDelivery,
} from '@tabler/icons-react';

// Roles that should only see their designated section (Operations or Accounts).
// Items tagged with `excludeRoles` will be hidden for those roles.
const SECTION_RESTRICTED_ROLES = ['operations_manager', 'accounts'];
const ACCOUNTS_ONLY_ROLES = ['accounts'];
const OPERATIONS_ONLY_ROLES = ['operations_manager'];

const ErpMenuItems = [
  {
    navlabel: true,
    subheader: 'CRM',
    excludeRoles: SECTION_RESTRICTED_ROLES,
  },
  {
    id: uniqueId(),
    title: 'Dashboard',
    icon: IconLayoutDashboard,
    href: '/erp/dashboard',
    permission: 'leads.read',
    adminDashboardOnly: true,
    excludeRoles: SECTION_RESTRICTED_ROLES,
  },
  {
    id: uniqueId(),
    title: 'Clients & Vendors',
    icon: IconAddressBook,
    href: '/erp/contacts',
    permission: 'contacts.read',
    excludeRoles: SECTION_RESTRICTED_ROLES,
    children: [
      { id: uniqueId(), title: 'Contacts', icon: IconPoint, href: '/erp/contacts', permission: 'contacts.read', excludeRoles: SECTION_RESTRICTED_ROLES },
      { id: uniqueId(), title: 'Clients', icon: IconPoint, href: '/erp/companies', permission: 'companies.read', excludeRoles: SECTION_RESTRICTED_ROLES },
      { id: uniqueId(), title: 'Vendors', icon: IconPoint, href: '/erp/suppliers', permission: 'suppliers.read', excludeRoles: SECTION_RESTRICTED_ROLES },
    ],
  },
  {
    id: uniqueId(),
    title: 'Leads & Deals',
    icon: IconBriefcase,
    href: '/erp/leads',
    permission: 'leads.read',
    excludeRoles: SECTION_RESTRICTED_ROLES,
    children: [
      { id: uniqueId(), title: 'Leads', icon: IconPoint, href: '/erp/leads', permission: 'leads.read', excludeRoles: SECTION_RESTRICTED_ROLES },
      { id: uniqueId(), title: 'Deals', icon: IconPoint, href: '/erp/deals', permission: 'deals.read', excludeRoles: SECTION_RESTRICTED_ROLES },
    ],
  },
  {
    id: uniqueId(),
    title: 'Service and Purchase',
    icon: IconReceipt,
    href: '/erp/quotations',
    permission: 'deals.read',
    excludeRoles: SECTION_RESTRICTED_ROLES,
    children: [
      {
        id: uniqueId(),
        title: 'Quotations',
        icon: IconFileText,
        href: '/erp/quotations',
        permission: 'deals.read',
        excludeRoles: SECTION_RESTRICTED_ROLES,
        children: [
          { id: uniqueId(), title: 'Service Quotation', icon: IconPoint, href: '/erp/quotations', permission: 'deals.read', excludeRoles: SECTION_RESTRICTED_ROLES },
          { id: uniqueId(), title: 'Client purchase quotations', icon: IconPoint, href: '/erp/client-purchase-quotations', permission: 'deals.read', excludeRoles: SECTION_RESTRICTED_ROLES },
          { id: uniqueId(), title: 'Vendor purchase quotations', icon: IconPoint, href: '/erp/vendor-purchase-quotations', permission: 'deals.read', excludeRoles: SECTION_RESTRICTED_ROLES },
        ],
      },
      {
        id: uniqueId(),
        title: 'Orders',
        icon: IconShoppingCart,
        href: '/erp/service-orders',
        permission: 'deals.read',
        excludeRoles: SECTION_RESTRICTED_ROLES,
        children: [
          { id: uniqueId(), title: 'Clients Service Orders', icon: IconPoint, href: '/erp/service-orders', permission: 'deals.read', excludeRoles: SECTION_RESTRICTED_ROLES },
          { id: uniqueId(), title: 'Clients Purchase Orders', icon: IconPoint, href: '/erp/client-purchase-orders', permission: 'deals.read', excludeRoles: SECTION_RESTRICTED_ROLES },
          { id: uniqueId(), title: 'Vendor Purchase Orders', icon: IconPoint, href: '/erp/supplier-purchase-orders', permission: 'deals.read', excludeRoles: SECTION_RESTRICTED_ROLES },
        ],
      },
    ],
  },
  {
    navlabel: true,
    subheader: 'Accounts',
    excludeRoles: OPERATIONS_ONLY_ROLES,
  },
  {
    id: uniqueId(),
    title: 'Deals',
    icon: IconBriefcase,
    href: '/erp/deals',
    permission: 'deals.read',
    includeRoles: ACCOUNTS_ONLY_ROLES,
  },
  {
    id: uniqueId(),
    title: 'Proforma invoices',
    icon: IconFileInvoice,
    href: '/erp/proforma-invoices',
    permission: 'deals.read',
    excludeRoles: OPERATIONS_ONLY_ROLES,
  },
  {
    id: uniqueId(),
    title: 'Tax invoices',
    icon: IconReceipt,
    href: '/erp/tax-invoices',
    permission: 'deals.read',
    excludeRoles: OPERATIONS_ONLY_ROLES,
  },
  {
    id: uniqueId(),
    title: 'Receivables',
    icon: IconCoin,
    href: '/erp/receivables',
    permission: 'deals.read',
    excludeRoles: OPERATIONS_ONLY_ROLES,
  },
  {
    id: uniqueId(),
    title: 'Payables',
    icon: IconTruckDelivery,
    href: '/erp/payables',
    permission: 'deals.read',
    excludeRoles: OPERATIONS_ONLY_ROLES,
  },
  {
    id: uniqueId(),
    title: 'Posted expenses',
    icon: IconWallet,
    href: '/erp/accounts/expenses',
    permission: 'deals.read',
    excludeRoles: OPERATIONS_ONLY_ROLES,
  },
  {
    id: uniqueId(),
    title: 'Work orders (Accounts)',
    icon: IconClipboardCheck,
    href: '/erp/accounts/work-orders',
    permission: 'deals.read',
    excludeRoles: OPERATIONS_ONLY_ROLES,
  },
  {
    navlabel: true,
    subheader: 'Operations',
    excludeRoles: ACCOUNTS_ONLY_ROLES,
  },
  {
    id: uniqueId(),
    title: 'Deals',
    icon: IconBriefcase,
    href: '/erp/deals',
    permission: 'deals.read',
    includeRoles: OPERATIONS_ONLY_ROLES,
  },
  {
    id: uniqueId(),
    title: 'Work Orders',
    icon: IconHammer,
    href: '/erp/work-orders',
    permission: 'deals.read',
    excludeRoles: ACCOUNTS_ONLY_ROLES,
  },
  {
    navlabel: true,
    subheader: 'Others',
    excludeRoles: SECTION_RESTRICTED_ROLES,
  },
  {
    id: uniqueId(),
    title: 'Products & Services',
    icon: IconPackage,
    href: '/erp/products',
    permission: 'products.read',
    excludeRoles: SECTION_RESTRICTED_ROLES,
  },
  {
    id: uniqueId(),
    title: 'Terms & Conditions',
    icon: IconFileText,
    href: '/erp/terms',
    permission: 'deals.read',
    excludeRoles: SECTION_RESTRICTED_ROLES,
  },
  {
    navlabel: true,
    subheader: 'Inspections',
    excludeRoles: SECTION_RESTRICTED_ROLES,
  },
  {
    id: uniqueId(),
    title: 'Inspection Requests',
    icon: IconClipboardCheck,
    href: '/erp/inspection-requests',
    permission: 'inspection_requests.read',
    excludeRoles: SECTION_RESTRICTED_ROLES,
  },
  {
    navlabel: true,
    subheader: 'Administration',
    excludeRoles: SECTION_RESTRICTED_ROLES,
  },
  {
    id: uniqueId(),
    title: 'Roles',
    icon: IconShield,
    href: '/erp/roles',
    permission: 'roles.read',
    excludeRoles: SECTION_RESTRICTED_ROLES,
  },
  {
    id: uniqueId(),
    title: 'Users',
    icon: IconUsers,
    href: '/erp/users',
    permission: 'users.read',
    excludeRoles: SECTION_RESTRICTED_ROLES,
  },
  {
    id: uniqueId(),
    title: 'Company Settings',
    icon: IconSettings,
    href: '/erp/settings/company',
    permission: 'users.read',
    excludeRoles: SECTION_RESTRICTED_ROLES,
  },
];

export default ErpMenuItems;
